import { randomUUID,createHash } from 'node:crypto';
import { storage } from './storage.mjs';
import { analyzeSameThing } from '../experiments/same-thing/service.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex');
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
async function bodyOf(request){if(request.method!=='POST')throw Object.assign(new Error('Use POST for this request.'),{status:405});const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw Object.assign(new Error('Cross-origin requests are not accepted.'),{status:403});if(!request.headers.get('content-type')?.startsWith('application/json'))throw Object.assign(new Error('Send JSON.'),{status:415});const text=await request.text();if(text.length>12000)throw Object.assign(new Error('Request is too large.'),{status:413});let body;try{body=JSON.parse(text)}catch{throw Object.assign(new Error('Invalid request.'),{status:400})}if(!body||typeof body!=='object'||Array.isArray(body))throw Object.assign(new Error('Invalid request.'),{status:400});return body}
const endpoint=handler=>async(request,context={},injectedStore)=>{try{return await handler(request,context,injectedStore)}catch(error){if(!error.status)console.error('Studio request failed:',error.name);return json({error:error.status?error.message:'The experiment is temporarily unavailable.'},error.status||503)}};
export const sameThing=endpoint(async(request,context,injectedStore)=>json(await analyzeSameThing(await bodyOf(request),injectedStore||storage(context)),201));
const emailPattern=/^[^\s@]{1,64}@[^\s@]{1,190}\.[^\s@]{2,24}$/;
export const emailCapture=endpoint(async(request,context,injectedStore)=>{const input=await bodyOf(request);if(input.company)return json({saved:true});const email=String(input.email||'').trim().toLowerCase();if(!emailPattern.test(email)||email.length>254)throw Object.assign(new Error('Enter a valid email address.'),{status:400});const experiment=['monthly','samething'].includes(input.requested_experiment)?input.requested_experiment:'monthly';const submittedUrl=typeof input.url==='string'?input.url.slice(0,1500):null;const db=injectedStore||storage(context),id=hash(email+'|'+experiment);await db.set('email-captures/'+id,{id:randomUUID(),email,submitted_url:submittedUrl,requested_experiment:experiment,created_at:new Date().toISOString()});return json({saved:true},201)});
const events=new Set(['same_thing_page_view','product_url_submitted','extraction_success','extraction_failed','comparison_generated','curated_comparison_viewed','outbound_alternative_click','share_clicked','email_submitted','samething_page_view','search_submitted','url_submitted','product_identified','provider_search_started','provider_search_success','provider_search_failed','used_result_clicked','refurb_result_clicked','previous_model_clicked','homepage_view','vehicle_search','search_results_view','vehicle_detail_view','dealer_link_clicked','deal_plan_started','deal_plan_checkout_started','deal_plan_purchased','deal_plan_viewed']);
export const studioEvent=endpoint(async(request,context,injectedStore)=>{const input=await bodyOf(request);if(!events.has(input.name))throw Object.assign(new Error('Unknown event.'),{status:400});const metadata={};if(input.metadata&&typeof input.metadata==='object'&&!Array.isArray(input.metadata))for(const [k,v] of Object.entries(input.metadata).slice(0,8))if(/^[a-z_]{1,40}$/.test(k)&&['string','number','boolean'].includes(typeof v))metadata[k]=String(v).slice(0,120);const row={id:randomUUID(),name:input.name,metadata,created_at:new Date().toISOString()};await (injectedStore||storage(context)).set('studio-events/'+row.id,row);return json({saved:true},201)});
